name: atividade3

on: [push]
  # configuração para pull requests
  # pull_request:
  #   paths-ignore:
  #     - '**.md'
  # push:
  #   branches:
  #     - main
  #     - releases/*
  #   paths-ignore:
  #     - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      
      - working-directory: ./Aula 4/ui-testing
        run: npm install
      - working-directory: ./Aula 4/ui-testing
        run: npm run test
      - working-directory: ./Aula 4/ui-testing
        run: npm run build
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./Aula 4/ui-testing
          build: npm run build
          start: npm start
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build